blog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<tag>[a-z]+)/$', views.posts_by_tag, name='posts_by_tag'),
]

my_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage.views import homepage
from feedback_form.views import contact

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
    url(r'^$', homepage),
    url(r'^contact/', contact),
]

blog/models.py
from django.db import models
from django.utils import timezone

class Tag(models.Model):
    name = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    published_date = models.DateTimeField(
        default=timezone.now)
    tags = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title

# class Comment(models.Model):
#     author = models.ForeignKey('auth.User')
#     title = models.ForeignKey(Post)
#     comment_text = models.TextField()
#     comment_published_date = models.DateTimeField(
#         default=timezone.now, blank=True, null=True)
#
#     def __str__(self):
#         return "{0} {1}".format(self.comment_text, self.comment_published_date)

feedback_form/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text',]
        widgets = {
            'comment_text': forms.Textarea(attrs={'cols': 120, 'rows': 2}),
        }

feedback_form/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, Tag

def post_list(request):
    posts_list = Post.objects.all()
    paginator = Paginator(posts_list, 5)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {'posts': posts,})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post,})

def posts_by_tag(request, tag):
    tag = Tag.objects.filter(name=tag)
    posts = Post.objects.filter(tags=tag)
    paginator = Paginator(posts, 5)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {'posts': posts})

feedback_form/views.py
from django.shortcuts import render
from django.core.mail import send_mail

from .forms import ContactForm

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']

            recipients = ['pavel.yansapov@gmail.com']

            send_mail(subject, message, sender, recipients)
            return render(request, 'feedback_form/thanks.html')

    else:
        form = ContactForm()

    return render(request, 'feedback_form/contact.html', {'form': form})

homepage/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage/about.html')

blog/templates/blog/post_detail.html
{% extends 'homepage/base.html' %}
{% load md2 %}
{% load pygmentify %}

{% block content %}

    <h3 class="ctitle"><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
    <p><csmall>Опубликовано: {{ post.published_date|date:"d.m.Y" }} | {% if post.tags.all %}Тэги:</csmall>
    {% for tag in post.tags.all %}
        <a class="btn-default" href="{% url 'posts_by_tag' tag=tag %}" role="button">{{ tag|title }}</a>
    {% endfor %}{% endif %}</p>

    {% pygment %}
    <p>{{ post.text|markdown }}</p>
    {% endpygment %}

    {% load disqus_tags %}
    {% disqus_show_comments %}

{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'homepage/base.html' %}
{% load md2 %}

{% block content %}
    {% for post in posts %}
        <h3 class="ctitle"><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h3>
        <p><csmall>Опубликовано: {{ post.published_date|date:"d.m.Y" }} | {% if post.tags.all %}Тэги:</csmall>
        {% for tag in post.tags.all %}
            <a class="btn-default" href="{% url 'posts_by_tag' tag=tag %}" role="button">{{ tag|title }}</a>
        {% endfor %}{% endif %}</p>
        <p>{{ post.text|markdown|truncatechars:400 }}</p>
        <p><a href="{% url 'post_detail' pk=post.pk %}">[ Читать полностью ]</a></p>
        <hr>
        <div class="spacing"></div>
    {% endfor %}

    <div class="text-center">
        <ul class="pagination">
            <li class="{% if not posts.has_previous %}disabled{% endif %}"><a href="{% if posts.has_previous %}?page={{ posts.previous_page_number }}{% endif %}"><<</a></li>
            {% for number in posts.paginator.page_range %}
            <li class="{% if posts.number == number %}active{% endif %}"><a href="?page={{ number }}">{{ number }}</a></li>
            {% endfor %}
            <li class="{% if not posts.has_next %}disabled{% endif %}"><a href="{% if posts.has_next %}?page={{ posts.next_page_number }}{% endif %}">>></a></li>
        </ul>
    </div>
{% endblock content %}

blog/templates/blog/sidebar.html
<h4>Тэги</h4>
<hr>
<p>
    {% for tag in tags %}
        <a class="btn" href="{% url 'posts_by_tag' tag=tag.name %}" role="button">{{ tag.name|title }} <span class="badge">{{ tag.count_post }}</span></a>
    {% endfor %}
</p>

feedback_form/templates/feedback_form/contact.html
{% extends 'homepage/base.html' %}

{% block content %}
    <div class="col-lg-10">
        <form action="/contact/" method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                <label for="id_subject">Тема:</label>
                {{ form.subject.errors }}
                <div class="input-group">
                    <div class="input-group-addon"><i class="glyphicon glyphicon-tag"></i></div>
                    <input type="text" class="form-control" id="id_subject" name="subject" placeholder="Введите темы">
                </div>
            </div>
            <div class="form-group">
                <label for="id_sender">Email:</label>
                {{ form.sender.errors }}
                <div class="input-group">
                    <div class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></div>
                    <input type="email" class="form-control" id="id_sender" name="sender" placeholder="Введите email">
                </div>
            </div>
            <div class="form-group">
                <label for="id_message">Сообщение:</label>
                {{ form.message.errors }}
                    <textarea class="form-control" id="id_message" name="message" rows="10" placeholder="Введите сообщение"></textarea>
            </div>
            <button type="submit" class="btn btn-large btn-primary" formmethod="post">Отправить</button>
        </form>
    </div>
{% endblock %}

feedback_form/templates/feedback_form/thanks.html
{% extends 'homepage/base.html' %}

{% block content %}
    <p>Спасибо! Постараюсь ответить Вам в ближайшее время.</p>
{% endblock content %}

homepage/templates/homepage/about.html
{% extends 'homepage/base.html' %}

{% block content %}

    <h3 class="ctitle">Обо мне</h3>
    <p>Здравствуйте! Меня зовут Павел Янсапов, и я занимаюсь разработкой на Python.</p>
    <p>В <a href="blog/">блоге</a> планирую публиковать записи так или иначе связанные с программированием и IT.</p>
    <p>Для связи со мной Вы можете использовать <a href="contact/">специальную форму</a>, или же воспользоваться контактами и ссылками на социальные сети.</p>
    <hr>
    <div class="spacing"></div>
    <h3 class="ctitle">Используемые технологии</h3>
    <div class="technologies">
        <div class="col-xs-12" style="height:50px;"></div>
        <a href="https://www.djangoproject.com/"><i class="devicon-django-plain"></i></a>
        <a href="https://www.python.org/"><i class="devicon-python-plain-wordmark"></i></a>
        <a href=""><i class="devicon-html5-plain-wordmark"></i></a>
        <a href=""><i class="devicon-css3-plain-wordmark"></i></a>
        <div class="col-xs-12" style="height:50px;"></div>
        <a href="http://getbootstrap.com"><i class="devicon-bootstrap-plain-wordmark"></i></a>
        <a href="https://www.postgresql.org"><i class="devicon-postgresql-plain-wordmark"></i></a>
        <a href="https://en.wikipedia.org/wiki/Linux"><i class="devicon-linux-plain"></i></a>
        <a href="https://git-scm.com"><i class="devicon-git-plain"></i></a>
        <div class="col-xs-12" style="height:50px;"></div>
        <a href="http://lesscss.org/"><i class="devicon-less-plain-wordmark"></i></a>
    </div>

{% endblock content %}

homepage/templates/homepage/base.html
{% load staticfiles %}
{% load sidebar %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <title>PAVEL YANSAPOV</title>

    <!-- Bootstrap core CSS -->
{#    <link href="{%  static 'css/bootstrap.min.css' %}" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="{% static 'less/styles.less' %}" rel="stylesheet/less">#}
{#    <script src="{% static 'js/less.min.js' %}"></script>#}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'css/fruity.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/devicon.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/blog">PAVEL YANSAPOV.</a>
        </div>
        <div class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li class="{% if request.get_full_path == '/' %}active{% endif %}"><a href="/">ABOUT ME</a></li>
            <li class="{% if 'blog' in request.path %}active{% endif %}"><a href="/blog">BLOG</a></li>
            <li class="{% if 'contact' in request.path %}active{% endif %}"><a href="/contact">CONTACT</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- *****************************************************************************************************************
	 BLUE WRAP
	 ***************************************************************************************************************** -->
	<div class="blue">
	    <div class="container">
			<div class="row">
                {% if 'blog/post' in request.path %}
				<h3>Post.</h3>
                {% elif request.get_full_path == "/" %}
                <h3>About Me.</h3>
                {% elif 'contact' in request.path %}
				<h3>Contact.</h3>
                {% elif request.path|slice:"6:" != "" %}
                <h3>Posts with tag #{{ request.path|slice:"6:"|cut:"/"|title }}.</h3>
                {% elif 'blog' in request.path %}
                <h3>Blog List.</h3>
                {% endif %}
			</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /blue -->

	<!-- *****************************************************************************************************************
	 BLOG CONTENT
	 ***************************************************************************************************************** -->

	 <div class="container mtb">
	 	<div class="row">
            <div class="col-lg-8">
                {% block content %}
                {% endblock %}
            </div>
    <!-- *****************************************************************************************************************
	 SIDEBAR
	 ***************************************************************************************************************** -->
            <div class="col-lg-4">
		 		{% show_sidebar %}
	 		</div>
	 	</div><! --/row -->
	 </div><! --/container -->
    <!-- *****************************************************************************************************************
	 FOOTER
	 ***************************************************************************************************************** -->
	 <div id="footer">
	 	<div class="container">
		 	<div class="row">
		 		<div class="col-lg-4">
		 			<h4>Copyrights</h4>
                    <hr>
		 			<p>Copyright &copy; Pavel Yansapov 2016-2017</p>
		 		</div>
		 		<div class="col-lg-4">
		 			<h4>Social Links</h4><hr>
		 			<p>
		 				<a href="https://www.facebook.com/paul.anteee"><i class="fa fa-facebook"></i></a>
		 				<a href="https://www.linkedin.com/in/pavel-yansapov-019633129?trk=hp-identity-name"><i class="fa fa-linkedin"></i></a>
		 				<a href="skype:paul_anti?chat"><i class="fa fa-skype"></i></a>
		 				<a href="https://telegram.me/paul_anti"><i class="fa fa-telegram"></i></a>
		 				<a href="https://github.com/paulanti"><i class="fa fa-github-square"></i></a>
                        <a href="mailto:pavel.yansapov@gmail.com"><i class="fa fa-envelope"></i></a>
		 			</p>
		 		</div>
		 		<div class="col-lg-4">
		 			<h4>Contacts</h4><hr>
		 			<p><span class="glyphicon glyphicon-envelope"></span> pavel.yansapov@gmail.com</p>
                    <p><span class="glyphicon glyphicon-earphone"></span> +7 922 614-77-44 </p>
		 		</div>

		 	</div><! --/row -->
	 	</div><! --/container -->
	 </div><! --/footerwrap -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


  </body>
</html>